import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });
dotenv.config({ path: path.resolve(process.cwd(), '.env') });

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseKey);

// Curated high quality real estate photo collections
const PHOTOS = {
  apartments_modern: [
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
  ],
  apartments_luxury: [
    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1200&q=80',
  ],
  houses_campestre: [
    'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1200&q=80',
  ],
  houses_urban: [
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80',
  ],
  commercial: [
    'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
  ],
  studios: [
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=1200&q=80',
  ]
};

function makeGallery(urls: string[]) {
  return urls.map((url, idx) => ({
    id: `img-${Date.now()}-${idx}-${Math.random().toString(36).substring(2, 7)}`,
    url,
    title: `Foto ${idx + 1}`,
    is_cover: idx === 0,
    order: idx
  }));
}

async function seed() {
  console.log('🏘️ Starting Real Estate Seeding for Praxis Inmobiliaria (Ibagué, Colombia)...');

  // 1. Find Organization
  const { data: org, error: orgErr } = await supabase
    .from('organizations')
    .select('id, name, slug')
    .or('slug.eq.praxis-inmobiliaria,name.ilike.%Praxis Inmobiliaria%')
    .maybeSingle();

  if (!org) {
    console.error('❌ Could not find organization Praxis Inmobiliaria:', orgErr);
    process.exit(1);
  }

  console.log(`✅ Found Target Organization: "${org.name}" (ID: ${org.id})`);

  // 2. Ensure Categories Exist
  const defaultCategories = [
    { name: 'Apartamentos', slug: 'apartamentos', icon: 'Building2', color: '#0284c7', order_index: 1 },
    { name: 'Casas', slug: 'casas', icon: 'Home', color: '#10b981', order_index: 2 },
    { name: 'Oficinas & Locales Comerciales', slug: 'oficinas-locales', icon: 'Store', color: '#8b5cf6', order_index: 3 },
    { name: 'Lotes & Fincas', slug: 'lotes-fincas', icon: 'Trees', color: '#f59e0b', order_index: 4 },
    { name: 'Proyectos Sobre Planos', slug: 'proyectos-sobre-planos', icon: 'HardHat', color: '#ec4899', order_index: 5 }
  ];

  for (const cat of defaultCategories) {
    await supabase.from('service_categories').upsert({
      organization_id: org.id,
      name: cat.name,
      slug: cat.slug,
      icon: cat.icon,
      color: cat.color,
      order_index: cat.order_index,
      is_active: true,
      scope: 'organization'
    }, { onConflict: 'organization_id,slug' });
  }

  const { data: catList } = await supabase
    .from('service_categories')
    .select('id, name, slug')
    .eq('organization_id', org.id);

  const catMap = new Map((catList || []).map(c => [c.slug, c.id]));
  const catApartamentos = catMap.get('apartamentos');
  const catCasas = catMap.get('casas');
  const catOficinas = catMap.get('oficinas-locales');
  const catLotes = catMap.get('lotes-fincas');
  const catPlanos = catMap.get('proyectos-sobre-planos');

  console.log('✅ Categories verified and mapped.');

  // 3. Define 30 Properties (12 EN VENTA, 18 EN ARRIENDO)
  const properties = [
    // ==========================================
    // 12 PROPIEDADES EN VENTA
    // ==========================================
    {
      name: 'Penthouse Dúplex de Lujo en El Vergel',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 980000000,
      compare_at_price: 1050000000,
      operation_type: 'sale',
      property_type: 'penthouse',
      area_total_m2: 240,
      area_built_m2: 215,
      bedrooms: 4,
      bathrooms: 5,
      parking_cars: 3,
      parking_type: 'covered',
      stratum: '6',
      admin_fee: 650000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'El Vergel',
      address: 'Transversal 1 Sur # 78-45, Torre Altos del Vergel',
      photos: PHOTOS.apartments_luxury,
      common_areas: ['Piscina Climatizada', 'Jacuzzi Privado', 'Gimnasio Dotado', 'Zona BBQ', 'Coworking', 'Vigilancia 24/7', 'Ascensor Privado', 'Parqueadero de Visitantes'],
      badges: ['Destacado', 'Exclusivo'],
      description: 'Espectacular Penthouse Dúplex con acabados importados de primera categoría y terraza privada de 45m² con vista panorámica 360° sobre la meseta de Ibagué. Sala comedor de doble altura, chimenea a gas, cocina italiana con isla en cuarzo Calacatta y mármol en todos los baños. Cada habitación cuenta con baño privado y walk-in closet.'
    },
    {
      name: 'Casa Campestre Moderna en Conjunto Cerrado El Totumo',
      category: 'Casas',
      category_id: catCasas,
      base_price: 1350000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'house',
      area_total_m2: 950,
      area_built_m2: 340,
      bedrooms: 4,
      bathrooms: 5,
      parking_cars: 4,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 480000,
      antiquity: 'Menos de 1 año',
      kitchen_type: 'americana',
      city: 'Ibagué',
      neighborhood: 'El Totumo / Aparco',
      address: 'Km 3 Vía al Totumo, Condominio Campestre Los Samanes Casa 14',
      photos: PHOTOS.houses_campestre,
      common_areas: ['Piscina Privada con Playa', 'Jacuzzi Exterior', 'Kiosko BBQ', 'Cancha Múltiple', 'Senderos Ecológicos', 'Seguridad Privada 24/7', 'Planta Eléctrica Total'],
      badges: ['Destacado', 'Novedad'],
      description: 'Exclusiva residencia campestre de una sola planta diseñada con arquitectura bioclimática e iluminación natural. Cuenta con piscina privada sin fin, deck en teca, jardines zen, techos altos en maderas nobles, sistema de sonido integrado y paneles solares con ahorro energético del 70%.'
    },
    {
      name: 'Apartamento Familiar con Balcón en Calambeo',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 495000000,
      compare_at_price: 530000000,
      operation_type: 'sale',
      property_type: 'apartment',
      area_total_m2: 128,
      area_built_m2: 120,
      bedrooms: 3,
      bathrooms: 3,
      parking_cars: 2,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 380000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Calambeo',
      address: 'Calle 19 # 8-30, Reserva de Calambeo Torre 2 Apto 804',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Piscina Climatizada', 'Sauna & Turco', 'Salón de Eventos', 'Zona Infantil', 'Senderos Verdes', 'CCTV 24H', 'Parqueadero Visitantes'],
      badges: ['Oportunidad'],
      description: 'Hermoso apartamento ubicado en el pulmón verde de Ibagué, rodeado de naturaleza y clima fresco. Amplia sala comedor integrada con ventanales de piso a techo, balcón con vista a la cordillera, cocina abierta tipo isla, estudio independiente y 2 parqueaderos en línea más depósito.'
    },
    {
      name: 'Casa Tradicional de 2 Pisos en La Pola',
      category: 'Casas',
      category_id: catCasas,
      base_price: 680000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'house',
      area_total_m2: 260,
      area_built_m2: 245,
      bedrooms: 5,
      bathrooms: 4,
      parking_cars: 2,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 0,
      antiquity: 'Más de 10 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'La Pola',
      address: 'Calle 8 # 3-52 La Pola',
      photos: PHOTOS.houses_urban,
      common_areas: ['Patio Interior Colonial', 'Terraza Techada', 'Tanque de Reserva Subterráneo'],
      badges: ['Recomendado'],
      description: 'Imponente casa en el sector histórico y residencial de La Pola. Estructura sólida tradicional con amplios espacios, techos altos en machimbre, patio central con jardín y fuente, garaje doble cubierto, cuarto y baño de servicio, ideal para familia numerosa o sede corporativa/notarial.'
    },
    {
      name: 'Apartamento Minimalista a Estrenar en Piedra Pintada',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 340000000,
      compare_at_price: 365000000,
      operation_type: 'sale',
      property_type: 'apartment',
      area_total_m2: 86,
      area_built_m2: 80,
      bedrooms: 3,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 240000,
      antiquity: 'A estrenar (Sobre Planos)',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Piedra Pintada',
      address: 'Carrera 5 # 48-12, Edificio Mirador de Piedra Pintada',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Rooftop con Jacuzzi', 'Zona BBQ Panorámica', 'Lobby Tipo Hotel', 'Coworking', 'Gimnasio Fitness'],
      badges: ['Novedad', 'Descuento'],
      description: 'Apartamento de estreno con diseño vanguardista y distribución eficiente. Excelente iluminación natural, pisos en porcelanato de gran formato, cocina integral con barra tipo barra americana, luces LED empotradas y balcón amplio. Ubicación estratégica a pasos de centros comerciales y clínicas.'
    },
    {
      name: 'Lote Urbanizado en Condominio Campestre Picaleña',
      category: 'Lotes & Fincas',
      category_id: catLotes,
      base_price: 280000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'lot',
      area_total_m2: 600,
      area_built_m2: 0,
      bedrooms: 0,
      bathrooms: 0,
      parking_cars: 0,
      parking_type: 'uncovered',
      stratum: '4',
      admin_fee: 210000,
      antiquity: 'A estrenar (Sobre Planos)',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Picaleña / Sector Mirolindo',
      address: 'Km 5 Variante Ibagué - Bogotá, Condominio Hacienda del Sol Manzana D Lote 8',
      photos: PHOTOS.houses_campestre,
      common_areas: ['Club House', 'Piscina de 25m', 'Canchas de Tenis', 'Sede Social', 'Portería 24H', 'Redes Subterráneas'],
      badges: ['Oportunidad'],
      description: 'Magnífico lote plano de 600m² con todos los servicios públicos subterráneos listos para acometida (agua, energía, gas natural, fibra óptica). Condominio campestre de alta valorización con vías pavimentadas y club social campestre completo.'
    },
    {
      name: 'Edificio Comercial Rentable de 3 Pisos en Centro / Carrera 3ra',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 1850000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'commercial',
      area_total_m2: 520,
      area_built_m2: 490,
      bedrooms: 0,
      bathrooms: 6,
      parking_cars: 0,
      parking_type: 'none',
      stratum: '4',
      admin_fee: 0,
      antiquity: '5 a 10 años',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Centro Financiero',
      address: 'Carrera 3 # 12-65 Esquina Peatonal',
      photos: PHOTOS.commercial,
      common_areas: ['Subestación Eléctrica Propia', 'Tanque de Reserva de 15.000L', 'Cortinas Eléctricas de Seguridad'],
      badges: ['Destacado', 'Exclusivo'],
      description: 'Inmueble comercial de alta rentabilidad ubicado sobre el eje peatonal de mayor tráfico de la ciudad. Primer piso local comercial de 180m² con vitrinas de cristal templado, segundo y tercer piso con plantas libres para oficinas o consultorios médicos. Renta estimada de $14.000.000 COP/mes.'
    },
    {
      name: 'Apartamento Tipo Club House en Santa Ana',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 385000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'apartment',
      area_total_m2: 95,
      area_built_m2: 90,
      bedrooms: 3,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 260000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Santa Ana',
      address: 'Calle 60 # 18-40, Conjunto Palmetto Santa Ana',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Parque Acuático Infantil', 'Piscina Adultos', 'Cancha Sintética de Fútbol', 'Sala de Cine', 'Gimnasio Crossfit', 'Vigilancia 24/7'],
      badges: ['Más Vendido'],
      description: 'Apartamento moderno con excelente distribución y vista interior protegida del sol de la tarde. 3 alcobas con closets empotrados, habitación principal con baño y vestier, balcón amplio, cocina abierta y parqueadero privado cubierto en sótano.'
    },
    {
      name: 'Casa Quinta con Frutales y Piscina en El Salado',
      category: 'Casas',
      category_id: catCasas,
      base_price: 750000000,
      compare_at_price: 800000000,
      operation_type: 'sale',
      property_type: 'house',
      area_total_m2: 1200,
      area_built_m2: 280,
      bedrooms: 4,
      bathrooms: 4,
      parking_cars: 6,
      parking_type: 'uncovered',
      stratum: '3',
      admin_fee: 0,
      antiquity: '5 a 10 años',
      kitchen_type: 'semi_integral',
      city: 'Ibagué',
      neighborhood: 'El Salado / Chucuní',
      address: 'Vereda Chucuní Lote San Miguel',
      photos: PHOTOS.houses_campestre,
      common_areas: ['Piscina Privada', 'Árboles Frutales en Producción', 'Zona de Asados', 'Casa de Mayordomo Independiente', 'Kiosko'],
      badges: ['Oportunidad', 'Descuento'],
      description: 'Hermosa finca de descanso a tan solo 15 minutos del centro de Ibagué. Terreno de 1.200m² con árboles de mango, cítricos y aguacate, piscina privada recién remodelada, quiosco campestre, agua de acueducto y aljibe propio. Ideal para fines de semana o renta turística Airbnb.'
    },
    {
      name: 'Apartamento de Lujo en Torre Prados del Norte',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 560000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'apartment',
      area_total_m2: 142,
      area_built_m2: 135,
      bedrooms: 3,
      bathrooms: 4,
      parking_cars: 2,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 420000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Prados del Norte',
      address: 'Carrera 7 # 64-15, Torre Prados Luxury',
      photos: PHOTOS.apartments_luxury,
      common_areas: ['Piscina Semiolímpica', 'Spa con Turco', 'Squash', 'Salón de Juegos', 'Lobby Doble Altura', 'Seguridad Privada 24/7'],
      badges: ['Destacado'],
      description: 'Exclusivo apartamento en una de las zonas residenciales más valorizadas de Ibagué. Acabados premium, alcoba de servicio con baño, estar de televisión independiente, balcón con punto de gas para BBQ y doble parqueadero independiente.'
    },
    {
      name: 'Local Comercial en Plazoleta Mall Calle 60',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 420000000,
      compare_at_price: null,
      operation_type: 'sale',
      property_type: 'commercial',
      area_total_m2: 68,
      area_built_m2: 68,
      bedrooms: 0,
      bathrooms: 1,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 520000,
      antiquity: '1 a 5 años',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Milla de Oro / Calle 60',
      address: 'Calle 60 # 10-25 Local 108',
      photos: PHOTOS.commercial,
      common_areas: ['Parqueadero Comercial Clientes', 'Plazoleta Gourmet', 'Vigilancia Armada 24H', 'Circuito Cerrado de Cámaras'],
      badges: ['Destacado'],
      description: 'Local comercial en el corazón de la Milla de Oro de Ibagué. Fachada en vidrio templado de piso a techo, punto de agua y desagüe para cafetería o consultorio estético, mezanine de 20m² para bodega u oficina administrativa.'
    },
    {
      name: 'Proyecto Sobre Planos - Torre Solaris El Vergel (Entrega 2027)',
      category: 'Proyectos Sobre Planos',
      category_id: catPlanos,
      base_price: 395000000,
      compare_at_price: 430000000,
      operation_type: 'sale',
      property_type: 'apartment',
      area_total_m2: 98,
      area_built_m2: 92,
      bedrooms: 3,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 280000,
      antiquity: 'A estrenar (Sobre Planos)',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'El Vergel',
      address: 'Av. Ambalá con Calle 77, Proyecto Solaris Torre 1',
      photos: PHOTOS.apartments_luxury,
      common_areas: ['Sky Lounge en Piso 18', 'Piscina Infinity Edge', 'Zona Pet Shower', 'Coworking Space', 'Yoga Studio', 'Cancha de Pádel'],
      badges: ['Novedad', 'Oportunidad'],
      description: 'Preventa exclusiva con facilidades de pago en cuota inicial a 30 meses sin intereses. Apartamento de 98m² con certificación ambiental EDGE, ventanería termoacústica y amenidades de resort en el exclusivo sector de El Vergel.'
    },

    // ==========================================
    // 18 PROPIEDADES EN ARRIENDO
    // ==========================================
    {
      name: 'Apartamento Amoblado Ejecutivo en El Vergel',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 3600000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'apartment',
      area_total_m2: 110,
      area_built_m2: 105,
      bedrooms: 3,
      bathrooms: 3,
      parking_cars: 2,
      parking_type: 'covered',
      stratum: '6',
      admin_fee: 550000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'El Vergel',
      address: 'Calle 78 # 2B-10, Edificio Mirador del Vergel Apto 502',
      photos: PHOTOS.apartments_luxury,
      common_areas: ['Piscina Climatizada', 'Gimnasio', 'Turco', 'Vigilancia 24/7', 'Ascensor Directo'],
      badges: ['Destacado'],
      description: 'Elegante apartamento totalmente amoblado y dotado con electrodomésticos de gama alta, internet fibra óptica de 300MB, Smart TVs en todas las habitaciones y terraza con juego de comedor exterior. Canon incluye administración.'
    },
    {
      name: 'Apartaestudio Moderno para Profesionales en Piedra Pintada',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1350000,
      compare_at_price: 1450000,
      operation_type: 'rent',
      property_type: 'studio',
      area_total_m2: 45,
      area_built_m2: 42,
      bedrooms: 1,
      bathrooms: 1,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 160000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Piedra Pintada',
      address: 'Carrera 4C # 46-28, Edificio Studio 46 Apto 304',
      photos: PHOTOS.studios,
      common_areas: ['Terraza BBQ en Azotea', 'Lavandería Comunal', 'Lobby con Recepción', 'CCTV 24H'],
      badges: ['Más Vendido'],
      description: 'Acogedor apartaestudio de ambiente integrado con balcón exterior, closet amplio, cocina tipo americana con barra en granito, zona de ropas independiente y parqueadero cubierto para carro o moto.'
    },
    {
      name: 'Casa en Conjunto Cerrado con Piscina en Santa Ana',
      category: 'Casas',
      category_id: catCasas,
      base_price: 2800000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'house',
      area_total_m2: 175,
      area_built_m2: 160,
      bedrooms: 4,
      bathrooms: 4,
      parking_cars: 2,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 320000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Santa Ana / Carrera 5ta',
      address: 'Carrera 5 # 58-30, Condominio Santa Ana Casa 28',
      photos: PHOTOS.houses_urban,
      common_areas: ['Piscina Adultos y Niños', 'Cancha Múltiple', 'Salón Social', 'Parque Infantil', 'Vigilancia 24 Horas'],
      badges: ['Recomendado'],
      description: 'Hermosa casa de 2 niveles en conjunto cerrado de ambiente familiar. Sala comedor independiente, cocina integral cerrada, patio trasero con techo corredizo, 4 alcobas con aire acondicionado instalado y parqueadero doble.'
    },
    {
      name: 'Oficina Corporativa en Centro Empresarial Milla de Oro',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 2200000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'commercial',
      area_total_m2: 60,
      area_built_m2: 60,
      bedrooms: 0,
      bathrooms: 1,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 340000,
      antiquity: '1 a 5 años',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Milla de Oro / Calle 60',
      address: 'Calle 60 con Carrera 5ta, Torre Empresarial Acomod Oficina 608',
      photos: PHOTOS.commercial,
      common_areas: ['Salas de Juntas Dotadas', 'Auditorio para 80 Personas', 'Baterías de Baños Comunales', '3 Ascensores de Alta Velocidad', 'Valet Parking'],
      badges: ['Destacado'],
      description: 'Oficina con divisiones modulares en vidrio templado, cableado estructurado categoría 6A, aire acondicionado central, iluminación LED, baño privado y vista hacia la avenida principal. Lista para ocupar.'
    },
    {
      name: 'Apartamento de 3 Alcobas con Balcón en Calambeo',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1950000,
      compare_at_price: 2100000,
      operation_type: 'rent',
      property_type: 'apartment',
      area_total_m2: 92,
      area_built_m2: 88,
      bedrooms: 3,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 280000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Calambeo',
      address: 'Carrera 1A # 18-60, Terrazas de Calambeo',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Piscina', 'Sendero Peatonal', 'Zona BBQ', 'Salón de Eventos', 'Portería 24/7'],
      badges: ['Descuento'],
      description: 'Excelente apartamento en piso alto con espectacular brisa y tranquilidad. Alcobas con piso laminado en madera, cocina con horno a gas y campana extractora, calentador de paso a gas y parqueadero cubierto en primer nivel.'
    },
    {
      name: 'Local Comercial con Terraza sobre Carrera 5ta con 42',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 4500000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'commercial',
      area_total_m2: 120,
      area_built_m2: 95,
      bedrooms: 0,
      bathrooms: 2,
      parking_cars: 2,
      parking_type: 'uncovered',
      stratum: '4',
      admin_fee: 0,
      antiquity: '5 a 10 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Piedra Pintada / Cra 5ta',
      address: 'Carrera 5 # 42-18 Sobre Avenida Principal',
      photos: PHOTOS.commercial,
      common_areas: ['Bahía de Parqueo Clientes', 'Punto de Gas Industrial', 'Trifásica'],
      badges: ['Destacado', 'Oportunidad'],
      description: 'Local comercial con alto impacto visual sobre la principal arteria vial de Ibagué. Cuenta con terraza frontal autorizada de 25m², salón principal con piso en granito pulido, 2 baños para clientes y espacio de cocina con trampa de grasas.'
    },
    {
      name: 'Apartamento Económico en Jordán 8va Etapa',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1100000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'apartment',
      area_total_m2: 68,
      area_built_m2: 65,
      bedrooms: 3,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'uncovered',
      stratum: '3',
      admin_fee: 140000,
      antiquity: '5 a 10 años',
      kitchen_type: 'semi_integral',
      city: 'Ibagué',
      neighborhood: 'Jordán 8va Etapa',
      address: 'Calle 69 # 14-20, Conjunto Rincones del Jordán',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Cancha de Baloncesto', 'Parque Infantil', 'Salón Comunal', 'Vigilancia 24 Horas'],
      badges: ['Oportunidad'],
      description: 'Cómodo apartamento en conjunto cerrado tradicional, cerca a almacenes Éxito, Homecenter y colegios. Cuenta con 3 habitaciones, closets metálicos, cocina semi-integral con gas domiciliario y parqueadero comunal asignado.'
    },
    {
      name: 'Casa Campestre Amoblada en El Vergel Alto',
      category: 'Casas',
      category_id: catCasas,
      base_price: 5200000,
      compare_at_price: 5800000,
      operation_type: 'rent',
      property_type: 'house',
      area_total_m2: 500,
      area_built_m2: 290,
      bedrooms: 4,
      bathrooms: 5,
      parking_cars: 3,
      parking_type: 'covered',
      stratum: '6',
      admin_fee: 620000,
      antiquity: '1 a 5 años',
      kitchen_type: 'americana',
      city: 'Ibagué',
      neighborhood: 'El Vergel',
      address: 'Calle 80 # 1 Sur-40, Condominio Pradera del Vergel',
      photos: PHOTOS.houses_campestre,
      common_areas: ['Piscina Privada', 'Zona BBQ Cubierta', 'Jacuzzi', 'Gimnasio del Conjunto', 'Seguridad Motorizada 24/7'],
      badges: ['Exclusivo', 'Descuento'],
      description: 'Exclusiva propiedad amoblada con diseño contemporáneo. Espacios abiertos integrados con el jardín exterior, piscina privada, alcoba máster con vestier y baño tipo spa con tina de hidromasajes. Incluye mantenimiento de piscina y jardín.'
    },
    {
      name: 'Apartamento en La Pola con Vista a las Montañas',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1650000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'apartment',
      area_total_m2: 85,
      area_built_m2: 80,
      bedrooms: 2,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 220000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'La Pola',
      address: 'Calle 6 # 3-40, Edificio Pola Colonial',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Terraza Mirador', 'Gimnasio', 'Salón Social', 'Portería 24H'],
      badges: ['Recomendado'],
      description: 'Hermoso apartamento en el tradicional barrio La Pola, a 5 minutos del centro y de los mejores cafés de la ciudad. Cuenta con 2 alcobas amplias, 2 baños modernos, cocina con barra americana y vista ininterrumpida al cañón del Combeima.'
    },
    {
      name: 'Apartaestudio Tipo Loft en Cádiz / Sector Médico',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1400000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'studio',
      area_total_m2: 48,
      area_built_m2: 48,
      bedrooms: 1,
      bathrooms: 1,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 175000,
      antiquity: 'Menos de 1 año',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Cádiz',
      address: 'Calle 33 # 4B-22, Edificio Cádiz Loft 402',
      photos: PHOTOS.studios,
      common_areas: ['Coworking con Café', 'Lavandería Automática', 'Rooftop con Asador', 'Ascensor'],
      badges: ['Novedad'],
      description: 'Moderno loft diseñado para médicos, estudiantes de posgrado o ejecutivos. Ubicado en el corazón del sector de la salud en Cádiz, cerca de clínicas y hospitales. Acabados industriales con techos a la vista y ventanal acústico.'
    },
    {
      name: 'Casa Campestre para Renta Temporal o Vivienda en Picaleña',
      category: 'Casas',
      category_id: catCasas,
      base_price: 3900000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'house',
      area_total_m2: 700,
      area_built_m2: 240,
      bedrooms: 4,
      bathrooms: 4,
      parking_cars: 4,
      parking_type: 'uncovered',
      stratum: '4',
      admin_fee: 350000,
      antiquity: '1 a 5 años',
      kitchen_type: 'americana',
      city: 'Ibagué',
      neighborhood: 'Picaleña',
      address: 'Km 2 Vía al Aeropuerto Perales, Condominio Campestre La Florida',
      photos: PHOTOS.houses_campestre,
      common_areas: ['Piscina Privada', 'Kiosko Bar', 'Zonas Verdes Amplias', 'Portería Blindada 24H', 'Cancha de Tenis del Conjunto'],
      badges: ['Destacado'],
      description: 'Espectacular casa campestre en arriendo ubicada cerca al Aeropuerto Perales. Clima cálido agradable, piscina privada con cascada, amplio jardín para mascotas y reuniones familiares. Opción amoblada o desocupada.'
    },
    {
      name: 'Bodega Comercial e Industrial en Sector Mirolindo',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 6800000,
      compare_at_price: 7500000,
      operation_type: 'rent',
      property_type: 'commercial',
      area_total_m2: 450,
      area_built_m2: 420,
      bedrooms: 0,
      bathrooms: 3,
      parking_cars: 4,
      parking_type: 'covered',
      stratum: '3',
      admin_fee: 0,
      antiquity: '5 a 10 años',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Zona Industrial Mirolindo',
      address: 'Carrera 48 Sur # 112-40 Manzana 2',
      photos: PHOTOS.commercial,
      common_areas: ['Muelle de Carga y Descarga', 'Piso de Alta Resistencia para Montacargas', 'Energía Trifásica 45 kVA', 'Oficinas Administrativas de 2 Pisos'],
      badges: ['Oportunidad', 'Descuento'],
      description: 'Bodega de almacenamiento y logística con triple altura (8.5 metros libres), portón para tractomulas, oficinas climatizadas con 2 baños y área de cafetería para personal. Excelente acceso a la variante Ibagué - Bogotá - Cali.'
    },
    {
      name: 'Apartamento Dúplex con Terraza en Interlaken',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 2600000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'apartment',
      area_total_m2: 130,
      area_built_m2: 118,
      bedrooms: 3,
      bathrooms: 3,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 310000,
      antiquity: '5 a 10 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Interlaken',
      address: 'Carrera 8 # 19-45, Edificio Interlaken Real',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Salón Social', 'Vigilancia 24/7', 'Ascensor'],
      badges: ['Recomendado'],
      description: 'Apartamento dúplex ubicado en el tradicional y céntrico barrio Interlaken. En el primer nivel sala comedor, cocina integral y 2 habitaciones; en el segundo nivel alcoba máster con vestier y terraza descubierta de 20m².'
    },
    {
      name: 'Consultorio Odontológico / Médico en Clínica Medicentro',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 1800000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'commercial',
      area_total_m2: 38,
      area_built_m2: 38,
      bedrooms: 0,
      bathrooms: 1,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 390000,
      antiquity: '1 a 5 años',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Cádiz',
      address: 'Carrera 4C # 32-15 Consultorio 302 Medicentro Cádiz',
      photos: PHOTOS.commercial,
      common_areas: ['Sala de Espera Común con Recepcionista', 'Baterías Sanitarias por Piso', 'Ascensor Camillero', 'Planta Eléctrica de Suplencia Total'],
      badges: ['Destacado'],
      description: 'Consultorio médico habilitado bajo normas de la Secretaría de Salud. Piso en vinilo hospitalario antibacterial, lavamanos quirúrgico, aire acondicionado inverter y parqueadero privado en sótano para el especialista.'
    },
    {
      name: 'Apartamento Familiar en Conjunto La Samaria',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1750000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'apartment',
      area_total_m2: 78,
      area_built_m2: 74,
      bedrooms: 3,
      bathrooms: 2,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 210000,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'La Samaria / Vía al Aeropuerto',
      address: 'Calle 100 # 8-40, Conjunto Samaria Club',
      photos: PHOTOS.apartments_modern,
      common_areas: ['Piscina Parque Acuático', 'Cancha de Pádel', 'Pista de Trote', 'Gimnasio Dotado', 'Zona de Mascotas', 'Seguridad 24H'],
      badges: ['Más Vendido'],
      description: 'Apartamento en la zona de mayor crecimiento y desarrollo urbano de Ibagué (La Samaria). Acabados modernos, balcón con vista abierta, cocina integral con barra americana y depósito privado.'
    },
    {
      name: 'Casa Residencial en Barrio Macarena Alta',
      category: 'Casas',
      category_id: catCasas,
      base_price: 2400000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'house',
      area_total_m2: 180,
      area_built_m2: 170,
      bedrooms: 4,
      bathrooms: 3,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '4',
      admin_fee: 0,
      antiquity: '5 a 10 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'Macarena Alta',
      address: 'Calle 41 # 4A-12',
      photos: PHOTOS.houses_urban,
      common_areas: ['Patio Interior con Jardín', 'Terraza en Tercer Piso con BBQ'],
      badges: ['Oportunidad'],
      description: 'Hermosa casa unifamiliar de 3 pisos sobre calle vehicular tranquila. Sala comedor amplia, cocina integral moderna, 4 alcobas con armarios empotrados, terraza social cubierta y garaje con portón eléctrico.'
    },
    {
      name: 'Apartaestudio Amoblado Incluye Servicios en La Pola',
      category: 'Apartamentos',
      category_id: catApartamentos,
      base_price: 1600000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'studio',
      area_total_m2: 40,
      area_built_m2: 38,
      bedrooms: 1,
      bathrooms: 1,
      parking_cars: 0,
      parking_type: 'none',
      stratum: '4',
      admin_fee: 0,
      antiquity: '1 a 5 años',
      kitchen_type: 'integral',
      city: 'Ibagué',
      neighborhood: 'La Pola',
      address: 'Carrera 4 # 7-18 Apto 201',
      photos: PHOTOS.studios,
      common_areas: ['Terraza con Vista al Cañón', 'Lavadora Comunal'],
      badges: ['Recomendado'],
      description: 'Apartaestudio amoblado de estilo nórdico. El canon mensual incluye los servicios públicos de agua, energía, gas domiciliario e internet Wi-Fi de alta velocidad. Cama doble con lencería, Smart TV, nevera y utensilios básicos de cocina.'
    },
    {
      name: 'Local en Zona Rosa Centro Comercial Acqua / Calle 60',
      category: 'Oficinas & Locales Comerciales',
      category_id: catOficinas,
      base_price: 3800000,
      compare_at_price: null,
      operation_type: 'rent',
      property_type: 'commercial',
      area_total_m2: 55,
      area_built_m2: 55,
      bedrooms: 0,
      bathrooms: 1,
      parking_cars: 1,
      parking_type: 'covered',
      stratum: '5',
      admin_fee: 490000,
      antiquity: '1 a 5 años',
      kitchen_type: 'tradicional',
      city: 'Ibagué',
      neighborhood: 'Milla de Oro',
      address: 'Calle 60 # 8-35 Local 214',
      photos: PHOTOS.commercial,
      common_areas: ['Seguridad Privada 24/7', 'Aire Acondicionado Común', 'Escaleras Eléctricas', 'Parqueadero de Clientes'],
      badges: ['Destacado'],
      description: 'Local comercial en el pasillo principal del segundo piso del centro comercial, frente a marcas ancla reconocidas. Excelente iluminación, vitrina en vidrio templado y piso en porcelanato de alto tráfico.'
    }
  ];

  console.log(`📦 Seeding ${properties.length} properties (12 Venta, 18 Arriendo)...`);

  let count = 0;
  for (const p of properties) {
    const gallery = makeGallery(p.photos);
    const coverUrl = p.photos[0];

    const reDetails = {
      operation_type: p.operation_type,
      property_type: p.property_type,
      area_total_m2: p.area_total_m2,
      area_built_m2: p.area_built_m2,
      bedrooms: p.bedrooms,
      bathrooms: p.bathrooms,
      parking_cars: p.parking_cars,
      parking_type: p.parking_type,
      stratum: p.stratum,
      admin_fee: p.admin_fee,
      antiquity: p.antiquity,
      kitchen_type: p.kitchen_type,
      city: p.city,
      department: 'Tolima',
      neighborhood: p.neighborhood,
      address: p.address,
      hide_exact_address: false,
      common_areas: p.common_areas,
      show_mortgage_calculator: true,
      virtual_tour_url: p.badges.includes('Exclusivo') ? 'https://my.matterport.com/show/?m=sample' : ''
    };

    const itemPayload = {
      organization_id: org.id,
      name: p.name,
      description: p.description,
      category: p.category,
      category_id: p.category_id,
      classification: 'real_estate',
      type: 'service',
      base_price: p.base_price,
      compare_at_price: p.compare_at_price,
      image_url: coverUrl,
      images: gallery,
      gallery_images: gallery,
      classification_metadata: {
        real_estate: reDetails,
        cta_type: 'whatsapp',
        price_label_type: 'price'
      },
      badges: [],
      is_active: true,
      is_visible_in_portal: true,
      seo_title: `${p.name} | Praxis Inmobiliaria Ibagué`,
      seo_description: `${p.name} en ${p.neighborhood}, Ibagué. ${p.operation_type === 'sale' ? 'Venta' : 'Arriendo'} por $${p.base_price.toLocaleString('es-CO')} COP. Contáctanos.`
    };

    const { error: insErr } = await supabase
      .from('service_catalog')
      .insert(itemPayload);

    if (insErr) {
      console.error(`❌ Error inserting "${p.name}":`, insErr.message);
    } else {
      count++;
      console.log(`[${count}/30] ✅ Inserted: [${p.operation_type.toUpperCase()}] ${p.name} ($${p.base_price.toLocaleString('es-CO')})`);
    }
  }

  console.log(`\n🎉 Successfully seeded ${count} of ${properties.length} real estate properties in Praxis Inmobiliaria!`);
}

seed().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
