/**
 * Tier 3: Cross-Feature Pairwise Interactions
 * Suite: t3-07-ai-copy-spec-tabs-enrich
 * Features: AI Copywriter & Enhancer × Expandable Specification Tabs
 */

import { expect, TestRegistry, TestSuiteResult } from '../harness/assertions';
import { generateAICopyWithResilience } from '../tier2-boundaries/t2-13-ai-timeout-fallback.test';
import { parseSpecificationTabs } from '../tier2-boundaries/t2-11-spec-tabs-empty.test';
import { UniversalCatalogItem } from '../harness/contracts';

export const suite = {
  name: 'T3-07: AI Copywriter × Specification Tabs Enrich',
  tier: 'Tier 3',
  feature: 'F13 x F11: AI Copywriter x Expandable Specification Tabs',
  tests: [
    {
      name: 'AI copy generation automatically populates Description and Key Features tabs',
      fn: async () => {
        const mockAiModel = async () =>
          JSON.stringify({
            title: 'Chaqueta de Cuero Motociclista 100% Genuina',
            description: 'Chaqueta de alta resistencia con protecciones CE nivel 2 y forro térmico desmontable.',
            bulletPoints: [
              'Cuero vacuno de 1.3mm de alta resistencia a la abrasión',
              'Protecciones certificadas CE en hombros y codos',
              'Cierres impermeables YKK sellados al calor',
            ],
            seoKeywords: ['chaqueta cuero', 'moto colombia', 'proteccion ce'],
          });

        const aiResult = await generateAICopyWithResilience({ itemName: 'Chaqueta Cuero' }, mockAiModel);
        expect(aiResult.success).toBe(true);

        const enrichedItem: Partial<UniversalCatalogItem> = {
          name: aiResult.title,
          description: aiResult.description,
          specifications: {
            features: aiResult.bulletPoints,
          },
        };

        const tabs = parseSpecificationTabs(enrichedItem.description, enrichedItem.specifications);
        expect(tabs).toHaveLength(2);
        expect(tabs[0].id).toBe('description');
        expect(tabs[0].content).toContain('Chaqueta de alta resistencia');
        expect(tabs[1].id).toBe('features');
        expect((tabs[1].content as string[])).toHaveLength(3);
        expect((tabs[1].content as string[])[0]).toContain('Cuero vacuno de 1.3mm');
      },
    },
    {
      name: 'AI Copywriter handles prompt with custom SLA deliverables seamlessly',
      fn: async () => {
        const mockAgencyAi = async () =>
          JSON.stringify({
            title: 'Auditoría SEO Integral y Estrategia de Contenidos',
            description: 'Diagnóstico técnico completo para escalar tráfico orgánico y ventas.',
            bulletPoints: ['Auditoría On-page de 150 puntos', 'Análisis de brecha de palabras clave', 'Hoja de ruta a 90 días'],
          });

        const aiResult = await generateAICopyWithResilience({ itemName: 'Auditoría SEO' }, mockAgencyAi);
        const specs = {
          features: aiResult.bulletPoints,
          deliverables: ['Informe ejecutivo en PDF', 'Acceso a Looker Studio', 'Sesión de entrega 1h por Google Meet'],
          warranty: '30 días de soporte post-entrega.',
        };

        const tabs = parseSpecificationTabs(aiResult.description, specs);
        expect(tabs).toHaveLength(4);
        expect(tabs.map((t) => t.id)).toEqual(['description', 'features', 'deliverables', 'warranty']);
      },
    },
    {
      name: 'AI fallback output formats valid Specification Tabs when model is offline',
      fn: async () => {
        const aiResult = await generateAICopyWithResilience({ itemName: 'Curso de React 19' });
        expect(aiResult.fallbackUsed).toBe(true);

        const tabs = parseSpecificationTabs(aiResult.description, { features: aiResult.bulletPoints });
        expect(tabs).toHaveLength(2);
        expect(tabs[0].id).toBe('description');
        expect(tabs[1].id).toBe('features');
      },
    },
    {
      name: 'Sanitizes HTML tags generated by AI models before rendering tabs',
      fn: async () => {
        const mockModelWithHtml = async () =>
          JSON.stringify({
            title: 'Producto Tech',
            description: '<b>Descripción en negrita</b> con <script>alert(1)</script> contenido limpio.',
            bulletPoints: ['<i>Feature 1</i>', 'Feature 2 con <img src=x onerror=alert(2)> imagen'],
          });

        const aiResult = await generateAICopyWithResilience({ itemName: 'Tech' }, mockModelWithHtml);
        const tabs = parseSpecificationTabs(aiResult.description, { features: aiResult.bulletPoints });

        expect(tabs[0].content).not.toContain('<script>');
        const features = tabs[1].content as string[];
        expect(features[1]).not.toContain('<img');
      },
    },
    {
      name: 'Preserves SEO keywords in item specifications for dynamic meta tags',
      fn: async () => {
        const mockAiModel = async () =>
          JSON.stringify({
            title: 'Mesa Roble',
            description: 'Mesa de centro rústica.',
            bulletPoints: ['Roble macizo'],
            seoKeywords: ['mesa roble', 'muebles bogota', 'madera maciza'],
          });

        const aiResult = await generateAICopyWithResilience({ itemName: 'Mesa' }, mockAiModel);
        expect(aiResult.seoKeywords).toHaveLength(3);
        expect(aiResult.seoKeywords).toContain('mesa roble');
      },
    },
  ],
};

export async function runSuite(): Promise<TestSuiteResult> {
  const registry = new TestRegistry();
  registry.setSuite(suite.name, 'tier3');
  for (const t of suite.tests) {
    registry.addTest(t.name, t.fn);
  }
  return registry.runSuite();
}
