-- Create platform_settings table (Singleton)
CREATE TABLE IF NOT EXISTS public.platform_settings (
    id bigint generated by default as identity primary key,
    agency_name text NOT NULL DEFAULT 'Pixy',
    main_logo_url text, -- Dashboard / Sidebar
    portal_logo_url text, -- Client Portal
    favicon_url text, -- Browser Tab (Isotipo)
    brand_color_primary text DEFAULT '#4F46E5', -- Indigo-600
    brand_color_secondary text DEFAULT '#EC4899', -- Pink-500
    login_background_url text,
    social_links jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Constraint to ensure only one row (Singleton)
    CONSTRAINT platform_settings_singleton_check CHECK (id = 1)
);

-- Enable RLS
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;

-- 1. DROP existing policies if any to avoid conflicts during re-run
DROP POLICY IF EXISTS "Everyone can read platform settings" ON public.platform_settings;
DROP POLICY IF EXISTS "Admins can update platform settings" ON public.platform_settings;
DROP POLICY IF EXISTS "Service role manages platform settings" ON public.platform_settings;

-- 2. Policy: Everyone can read platform settings (public face)
CREATE POLICY "Everyone can read platform settings" 
    ON public.platform_settings FOR SELECT 
    USING (true);

-- 3. Policy: Only Service Role can update/insert (via Server Actions)
-- We removed the check for public.users since it doesn't exist.
-- Updates should be done via `updatePlatformSettings` action which uses supabaseAdmin.
CREATE POLICY "Service role manages platform settings"
    ON public.platform_settings FOR ALL
    USING (
        auth.jwt() ->> 'role' = 'service_role'
    );

-- Insert default row (id=1)
INSERT INTO public.platform_settings (id, agency_name)
VALUES (1, 'Pixy')
ON CONFLICT (id) DO NOTHING;
