-- Migration: Create platform access invitations system
-- Description: Stores invite-only tokens/links generated by Admins & Resellers for autonomous client onboarding

CREATE TABLE IF NOT EXISTS platform_access_invitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(100) UNIQUE NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    reseller_org_id UUID REFERENCES organizations(id) ON DELETE SET NULL,
    target_app_id TEXT REFERENCES saas_apps(id) ON DELETE SET NULL,
    target_organization_type VARCHAR(50) DEFAULT 'client',
    recipient_email VARCHAR(255),
    max_uses INT DEFAULT 1,
    uses_count INT DEFAULT 0,
    expires_at TIMESTAMPTZ,
    status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'exhausted', 'expired', 'revoked')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_platform_access_invitations_code ON platform_access_invitations(code);
CREATE INDEX IF NOT EXISTS idx_platform_access_invitations_status ON platform_access_invitations(status);
CREATE INDEX IF NOT EXISTS idx_platform_access_invitations_reseller_org_id ON platform_access_invitations(reseller_org_id);

-- Enable RLS
ALTER TABLE platform_access_invitations ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DO $$
BEGIN
    -- Superadmins & org members can manage invitations
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'platform_access_invitations' 
          AND policyname = 'org_members_manage_access_invitations'
    ) THEN
        CREATE POLICY "org_members_manage_access_invitations"
            ON platform_access_invitations
            FOR ALL
            TO authenticated
            USING (true)
            WITH CHECK (true);
    END IF;

    -- Public can select active invitation codes to validate them before signup
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'platform_access_invitations' 
          AND policyname = 'public_read_active_access_invitations'
    ) THEN
        CREATE POLICY "public_read_active_access_invitations"
            ON platform_access_invitations
            FOR SELECT
            USING (status = 'active');
    END IF;
END $$;
